apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
    team: ${TEAM_NAME}
---
apiVersion: v1
kind: Secret
metadata:
  name: ${APP_NAME}-secrets
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
    team: ${TEAM_NAME}
type: Opaque
data:
  google-service-account.json: ${GOOGLE_SERVICE_ACCOUNT}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
    team: ${TEAM_NAME}
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        team: ${TEAM_NAME}
        version: ${VERSION}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9001"
    spec:
      serviceAccount: ${APP_NAME}
      terminationGracePeriodSeconds: 300
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: In
                values:
                - "true"
      containers:
      - name: ${APP_NAME}
        image: estafette/estafette-gke-node-recycler:${GO_PIPELINE_LABEL}
        ports:
        - name: prom-metrics
          containerPort: 9001
        env:
        - name: DRAIN_TIMEOUT
          value: "${DRAIN_TIMEOUT}"
        - name: INTERVAL
          value: "${INTERVAL}"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/app-secrets/google-service-account.json
        resources:
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
        livenessProbe:
          httpGet:
            path: /metrics
            port: prom-metrics
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
        - name: app-secrets
          mountPath: /etc/app-secrets
      volumes:
      - name: app-secrets
        secret:
          secretName: ${APP_NAME}-secrets