apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: estafette-gke-node-recycler
  labels:
    app: estafette-gke-node-recycler
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - delete
- apiGroups: [""] # "" indicates the core API group
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: estafette-gke-node-recycler
  labels:
    app: estafette-gke-node-recycler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: estafette-gke-node-recycler
subjects:
- kind: ServiceAccount
  name: estafette-gke-node-recycler
  namespace: estafette
